import { Event, User } from "./types";

export const currentUser: User = {
  id: "user-1",
  firstName: "Alex",
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
  isVerified: true,
  eventsHosted: 3,
  eventsAttended: 12,
  bio: "Love meeting new people through shared experiences. Coffee enthusiast & weekend hiker.",
};

export const mockEvents: Event[] = [
  {
    id: "evt-1",
    title: "Sunday Morning Hike at Golden Gate Park",
    category: "Outdoor",
    date: "2026-01-12",
    time: "09:00 AM",
    area: "Richmond, SF",
    capacity: 12,
    attendees: 7,
    price: "Free",
    isPublic: true,
    lat: 37.7694,
    lng: -122.4862,
    host: {
      id: "host-1",
      firstName: "Sarah",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
      isVerified: true,
      eventsHosted: 15,
      eventsAttended: 24,
    },
    description: "Join us for a casual 5-mile morning hike through Golden Gate Park. We'll meet at the main entrance and explore some beautiful trails. Perfect for all skill levels!",
    rules: ["Be on time", "Bring water", "Respect nature", "Be friendly"],
  },
  {
    id: "evt-2",
    title: "Dinner Party: Mediterranean Night",
    category: "Food & Dining",
    date: "2026-01-10",
    time: "07:00 PM",
    area: "Mission District, SF",
    capacity: 8,
    attendees: 6,
    price: 25,
    isPublic: false,
    lat: 37.7599,
    lng: -122.4148,
    host: {
      id: "host-2",
      firstName: "Marcus",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
      isVerified: true,
      eventsHosted: 8,
      eventsAttended: 19,
    },
    description: "An evening of delicious Mediterranean cuisine at my apartment. I'll be cooking Greek and Turkish dishes. BYOB welcome!",
    rules: ["RSVP required", "Let me know about dietary restrictions", "Bring a dish if you'd like"],
  },
  {
    id: "evt-3",
    title: "Pickup Basketball Game",
    category: "Sports",
    date: "2026-01-08",
    time: "05:30 PM",
    area: "SoMa, SF",
    capacity: 10,
    attendees: 8,
    price: "Free",
    isPublic: true,
    lat: 37.7749,
    lng: -122.4194,
    host: {
      id: "host-3",
      firstName: "Jordan",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
      isVerified: false,
      eventsHosted: 4,
      eventsAttended: 11,
    },
    description: "Weekly pickup basketball at the local court. All skill levels welcome. We usually play for about 2 hours.",
    rules: ["Bring your own water", "Be respectful", "Have fun!"],
  },
  {
    id: "evt-4",
    title: "Board Game Night",
    category: "Social",
    date: "2026-01-11",
    time: "07:30 PM",
    area: "Nob Hill, SF",
    capacity: 6,
    attendees: 4,
    price: "Free",
    isPublic: true,
    lat: 37.7928,
    lng: -122.4155,
    host: {
      id: "host-4",
      firstName: "Emma",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop",
      isVerified: true,
      eventsHosted: 12,
      eventsAttended: 18,
    },
    description: "Cozy board game night at my place. I have Catan, Ticket to Ride, Codenames, and more. Snacks and drinks provided!",
    rules: ["No competitive stress", "Be kind", "Help clean up"],
  },
  {
    id: "evt-5",
    title: "Coffee & Coding Meetup",
    category: "Professional",
    date: "2026-01-09",
    time: "10:00 AM",
    area: "SOMA, SF",
    capacity: 15,
    attendees: 9,
    price: "Free",
    isPublic: true,
    lat: 37.7790,
    lng: -122.3952,
    host: {
      id: "host-5",
      firstName: "David",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop",
      isVerified: true,
      eventsHosted: 20,
      eventsAttended: 30,
    },
    description: "Casual meetup for developers. Work on your side projects, get help with bugs, or just chat about tech. Coffee shop setting.",
    rules: ["Buy your own coffee", "Respect the space", "Keep noise down"],
  },
  {
    id: "evt-6",
    title: "Sunset Photography Walk",
    category: "Creative",
    date: "2026-01-13",
    time: "05:00 PM",
    area: "Marina, SF",
    capacity: 10,
    attendees: 5,
    price: 15,
    isPublic: true,
    lat: 37.8044,
    lng: -122.4381,
    host: {
      id: "host-6",
      firstName: "Nina",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop",
      isVerified: true,
      eventsHosted: 7,
      eventsAttended: 14,
    },
    description: "Join me for a guided photography walk along the Marina. We'll capture the beautiful sunset and I'll share some tips and tricks. All camera types welcome!",
    rules: ["Bring your camera or phone", "Dress warmly", "Be patient"],
  },
];
